<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Sales Report</title>
    <style>
        @page {
            margin: 30px 20px;
        }

        body {
            font-family: sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            top: -20px;
            left: 0;
            right: 0;
            height: 60px;
            text-align: left;
            line-height: 60px;
            border-bottom: 1px solid #ddd;
        }

        header img {
            height: 40px;
            vertical-align: middle;
        }

        header .title {
            display: inline-block;
            vertical-align: middle;
            margin-left: 10px;
            font-size: 20px;
            font-weight: bold;
        }

        footer {
            position: fixed;
            bottom: -20px;
            left: 0;
            right: 0;
            height: 40px;
            text-align: center;
            line-height: 40px;
            font-size: 12px;
            color: #555;
            border-top: 1px solid #ddd;
        }

        table {
            border-collapse: collapse;
            width: 100%;
            table-layout: fixed;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 6px;
            word-wrap: break-word;
        }

        .summary {
            margin: 20px 0 20px 0;
        }

        .sub-table {
            margin-left: 10px;
            width: 100%;
            table-layout: fixed;
        }

        .section {
            page-break-inside: avoid;
            margin-bottom: 30px;
        }

        .chart {
            display: block;
            margin: 10px 0;
            max-width: 100%;
            height: auto;
        }

        h2,
        h3 {
            margin: 10px 0;
            page-break-after: avoid;
        }
    </style>
</head>

<body>

    <header>
        <img src="{{ public_path('images/logo.png') }}" alt="Company Logo">
        <span class="title">Sales Report</span>
    </header>

    <footer>
        Generated by OmKasirPOS
    </footer>

    <div class="summary">
        <p><strong>Period:</strong> {{ $from }} to {{ $to }}</p>
        <p><strong>Total Sales:</strong> Rp {{ number_format($totalSales, 0, ',', '.') }}</p>
        <p><strong>Total Transactions:</strong> {{ $transactionCount }}</p>
        <p><strong>Total Items Sold:</strong> {{ $itemsSold }}</p>
    </div>

    <div class="section">
        <h3>Top 5 Best-Selling Products</h3>
        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity Sold</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($topProducts as $product)
                    <tr>
                        <td>{{ $product->name }}</td>
                        <td>{{ $product->total_sold }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    @if ($pieChart)
        <div class="section">
            <h3>Sales Distribution</h3>
            <img src="{{ $pieChart }}" alt="Product Sales Distribution" class="chart">
        </div>
    @endif

    @if ($lineChart)
        <div class="section">
            <h3>Sales Trend</h3>
            <img src="{{ $lineChart }}" alt="Sales Trend" class="chart">
        </div>
    @endif

    <h3>Transaction Details</h3>
    @foreach ($transactions as $trx)
        <div class="section">
            <p>
                <strong>Transaction ID:</strong> {{ $trx->id }} <br>
                <strong>Date:</strong> {{ $trx->created_at->format('Y-m-d H:i') }} <br>
                <strong>Total:</strong> Rp {{ number_format($trx->total_price, 0, ',', '.') }}
            </p>

            <table class="sub-table">
                <thead>
                    <tr>
                        <th>Item Name</th>
                        <th>Unit Price</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($trx->items as $item)
                        <tr>
                            <td>{{ $item->name }}</td>
                            <td>Rp {{ number_format($item->price, 0, ',', '.') }}</td>
                            <td>{{ $item->quantity }}</td>
                            <td>Rp {{ number_format($item->price * $item->quantity, 0, ',', '.') }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    @endforeach

</body>

</html>
